$pdflatex = "xelatex --synctex=1 %O %S";
$pdf_mode = 1;
$dvi_mode = $postscript_mode = 0;

add_cus_dep('glo', 'gls', 0, 'makeglo2gls');
add_cus_dep('acn', 'acr', 0, 'makeglo2gls');
sub makeglo2gls {
        system("makeglossaries $_[0]");
}

